# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "HeyJhun"
description:	       "Jhun is bored at work so he studied how Jekyll works. He finds it cool, so HeyJhun was born. A personal blog about some things he wants to share because sometimes it is not easy to find someone to talk to about certain topics. haha! This site is created with Jekyll by Jhun Agustin."
author:              "Jhun Agustin"
footer:               "Hey"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
